apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: prod-
patches:
  - target:
      kind: ConfigMap
      name: agrayian-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: production
      - op: replace
        path: /data/SEED_DEMO
        value: "false"
