from uuid import UUID

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.identity import Permission, RolePermission, User, UserRole

PERMISSIONS = [
    ("command_center.read", "View command center"),
    ("accounts.read", "Read accounts"),
    ("accounts.write", "Write accounts"),
    ("contacts.read", "Read contacts"),
    ("contacts.write", "Write contacts"),
    ("leads.read", "Read leads"),
    ("leads.write", "Write leads"),
    ("leads.score", "Score leads"),
    ("opportunities.read", "Read opportunities"),
    ("opportunities.write", "Write opportunities"),
    ("opportunities.close", "Close opportunities"),
    ("tasks.read", "Read tasks"),
    ("tasks.write", "Write tasks"),
    ("icps.read", "Read ICPs"),
    ("icps.write", "Write ICPs"),
    ("users.read", "Read users"),
    ("users.write", "Write users"),
    ("teams.read", "Read teams"),
    ("teams.write", "Write teams"),
    ("roles.read", "Read roles"),
    ("flags.read", "Read flags"),
    ("flags.write", "Write flags"),
    ("audit.read", "Read audit"),
    ("ai.copilot", "Use copilot"),
    ("ai.research", "Run research"),
    ("ai.draft", "Draft communications"),
    ("ai.approvals.read", "Read approvals"),
    ("ai.approvals.decide", "Decide approvals"),
    ("knowledge.read", "Read knowledge"),
    ("knowledge.write", "Write knowledge"),
    ("admin.access", "Access administration"),
    ("markets.read", "Read markets"),
    ("markets.write", "Write markets"),
    ("signals.read", "Read intelligence signals"),
    ("signals.write", "Refresh intelligence signals"),
    ("acquisition.read", "Read acquisition"),
    ("acquisition.write", "Write acquisition"),
    ("acquisition.capture", "Capture inbound leads"),
    ("campaigns.read", "Read campaigns"),
    ("campaigns.write", "Write campaigns"),
    ("sequences.read", "Read sequences"),
    ("sequences.write", "Write sequences"),
    ("conversations.read", "Read conversations"),
    ("conversations.write", "Write conversations"),
    ("meetings.read", "Read meetings"),
    ("meetings.write", "Write meetings"),
    ("deals.read", "Read deal intelligence"),
    ("commercial.read", "Read commercial"),
    ("commercial.write", "Write quotes"),
    ("forecast.read", "Read forecast"),
    ("success.read", "Read success"),
    ("success.write", "Write success"),
    ("advocacy.read", "Read advocacy"),
    ("advocacy.write", "Write advocacy"),
    ("revops.read", "Read RevOps"),
    ("revops.write", "Write RevOps"),
    ("autonomy.read", "Read autonomous runs"),
    ("autonomy.write", "Start autonomous runs"),
]

ROLE_PERMISSIONS: dict[str, list[str]] = {
    "Super Admin": [p[0] for p in PERMISSIONS],
    "Tenant Admin": [p[0] for p in PERMISSIONS],
    "CEO": [p[0] for p in PERMISSIONS if not p[0].startswith("users.write")],
    "CRO": [p[0] for p in PERMISSIONS],
    "CMO": [
        "command_center.read",
        "accounts.read",
        "contacts.read",
        "leads.read",
        "leads.write",
        "leads.score",
        "icps.read",
        "ai.copilot",
        "knowledge.read",
        "markets.read",
        "markets.write",
        "signals.read",
        "signals.write",
        "acquisition.read",
        "acquisition.write",
        "acquisition.capture",
        "campaigns.read",
        "campaigns.write",
        "sequences.read",
        "sequences.write",
        "advocacy.read",
        "advocacy.write",
        "autonomy.read",
        "autonomy.write",
        "ai.approvals.read",
        "ai.approvals.decide",
    ],
    "Sales Director": [p[0] for p in PERMISSIONS if p[0] != "flags.write"],
    "Sales Manager": [p[0] for p in PERMISSIONS if p[0] not in {"flags.write", "users.write"}],
    "Sales Rep": [
        "command_center.read",
        "accounts.read",
        "accounts.write",
        "contacts.read",
        "contacts.write",
        "leads.read",
        "leads.write",
        "leads.score",
        "opportunities.read",
        "opportunities.write",
        "opportunities.close",
        "tasks.read",
        "tasks.write",
        "icps.read",
        "ai.copilot",
        "ai.research",
        "ai.draft",
        "knowledge.read",
        "knowledge.write",
        "ai.approvals.read",
        "markets.read",
        "signals.read",
        "acquisition.read",
        "acquisition.capture",
        "campaigns.read",
        "campaigns.write",
        "sequences.read",
        "sequences.write",
        "conversations.read",
        "conversations.write",
        "meetings.read",
        "meetings.write",
        "deals.read",
        "commercial.read",
        "commercial.write",
        "forecast.read",
        "success.read",
        "advocacy.read",
        "revops.read",
        "autonomy.read",
        "autonomy.write",
    ],
    "SDR Manager": [
        "command_center.read",
        "leads.read",
        "leads.write",
        "leads.score",
        "accounts.read",
        "contacts.read",
        "tasks.read",
        "tasks.write",
        "ai.copilot",
        "markets.read",
        "signals.read",
        "signals.write",
        "acquisition.read",
        "acquisition.write",
        "acquisition.capture",
        "campaigns.read",
        "campaigns.write",
        "sequences.read",
        "sequences.write",
        "conversations.read",
        "conversations.write",
        "autonomy.read",
        "autonomy.write",
    ],
    "SDR": [
        "command_center.read",
        "leads.read",
        "leads.write",
        "leads.score",
        "accounts.read",
        "contacts.read",
        "tasks.read",
        "tasks.write",
        "ai.copilot",
        "ai.draft",
        "markets.read",
        "signals.read",
        "acquisition.read",
        "acquisition.capture",
        "campaigns.read",
        "sequences.read",
        "sequences.write",
        "conversations.read",
        "autonomy.read",
    ],
    "Read Only": [
        "command_center.read",
        "accounts.read",
        "contacts.read",
        "leads.read",
        "opportunities.read",
        "tasks.read",
        "icps.read",
        "knowledge.read",
        "ai.approvals.read",
        "audit.read",
        "markets.read",
        "signals.read",
        "acquisition.read",
        "campaigns.read",
        "sequences.read",
        "conversations.read",
        "meetings.read",
        "deals.read",
        "commercial.read",
        "forecast.read",
        "success.read",
        "advocacy.read",
        "revops.read",
        "autonomy.read",
    ],
    "AI Agent": ["accounts.read", "contacts.read", "leads.read", "opportunities.read", "tasks.write", "autonomy.read"],
}


def user_permissions(db: Session, user: User) -> set[str]:
    if user.is_super_admin:
        return {p[0] for p in PERMISSIONS}
    rows = db.execute(
        select(Permission.key)
        .join(RolePermission, RolePermission.permission_id == Permission.id)
        .join(UserRole, UserRole.role_id == RolePermission.role_id)
        .where(UserRole.user_id == user.id)
    ).scalars()
    return set(rows)


def user_role_names(db: Session, user_id: UUID) -> list[str]:
    from app.models.identity import Role

    rows = db.execute(
        select(Role.name)
        .join(UserRole, UserRole.role_id == Role.id)
        .where(UserRole.user_id == user_id)
    ).scalars()
    return list(rows)
